apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: neutron-ovn
spec:
  label: neutron-ovn
  playbook: osp.edpm.neutron_ovn
  secrets:
  - neutron-ovn-agent-neutron-config
