apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: neutron-dhcp
spec:
  label: neutron-dhcp
  playbook: osp.edpm.neutron_dhcp
  secrets:
  - neutron-dhcp-agent-neutron-config
